version: "3.9"
services:
  postgres_sandbox:
    image: postgres:14
    ports:
      - '5432:5432'
    volumes:
      - ./sandbox-db:/var/lib/postgresql/data
      - ./sql/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  my_java_app:
    build:
      context: .
      dockerfile: Dockerfile-db
    ports:
      - "8080:8080"
    depends_on:
      - postgres_sandbox
    environment:
      - DB_URL=jdbc:postgresql://postgres_sandbox:5432/postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres

